fixup: remove trailing whitespace
note: the linter needs to be clearer about this. The error I got was this:

```
Error: Parse error on line 11:
...} -o {{{output.md}}` `- List all suppo
-----------------------^
Expecting 'NEWLINE', 'TEXT', 'DASH', 'BACKTICK', got 'COMMAND_TEXT'
pages/common/pandoc.md:10: TLDR103 Command example is missing its closing backtick
```