flameshot: missing : after description
Fixed LINE 11 and  16 formatting.
Error: Parse error on line 16:
... screen screenshot:  `flameshot full`
----------------------^

FIXED Expecting 'NEWLINE', 'BACKTICK', got 'TEXT'
pages/linux/flameshot.md:11: TLDR005 Example descriptions should end in a colon